### PR TITLE
dirlock: fix compilation on illumos.

### LINKED ISSUE #765: nsqd: won't compile on illumos
It seems that dirlock depends on some Linux specific syscalls, compilation of NSQd fails with the following output

```
# github.com/nsqio/nsq/internal/dirlock
../.go/src/github.com/nsqio/nsq/internal/dirlock/dirlock.go:28: undefined: syscall.Flock
../.go/src/github.com/nsqio/nsq/internal/dirlock/dirlock.go:28: undefined: syscall.LOCK_EX
../.go/src/github.com/nsqio/nsq/internal/dirlock/dirlock.go:28: undefined: syscall.LOCK_NB
../.go/src/github.com/nsqio/nsq/internal/dirlock/dirlock.go:37: undefined: syscall.Flock
../.go/src/github.com/nsqio/nsq/internal/dirlock/dirlock.go:37: undefined: syscall.LOCK_UN
```

### PR DESCRIPTION
**Pull request by i-sevostyanov**
Fixes #765

### CODE REVIEW

**Comment by ploxiln** [comment]
thanks

**Comment by i-sevostyanov** [comment]
Sorry for this. I'll fix it in a few days.

**Comment by ploxiln** [comment]
@i-sevostyanov I hope you don't mind if I push up a fix now since it's pretty tiny - #1205

**Comment by i-sevostyanov** [comment]
@ploxiln Thank you so much!

**Pull request merged**
