### PR TITLE
nsqadmin: fix nodes list links with ipv6 addresses

### PR DESCRIPTION
**Pull request by ploxiln**
alternative to #1179 

@andyxning please try this. I've clicked around and all links seem to work. (be sure to do a full refresh of nsqadmin, if you have the web page generated from a previous version already open in a tab.)

test setup:
  * `./build/nsqlookupd`
  * `./build/nsqd --broadcast-address=::1 --lookupd-tcp-address=[::1]:4160`
  * `curl localhost:4151/pub?topic=whatever -d '{"foo": 20}' ; echo`
  * `./build/nsq_tail --lookupd-http-address=[::1]:4161 --topic=whatever --channel=t3`
  * `./build/nsqadmin --lookupd-http-address=[::1]:4161`

cc @jehiah

### CODE REVIEW

**Comment by ploxiln** [comment]
note that the topic and channel pages do this, and it results in the correct links:

```
        {{#each nodes}}
        <tr>
            <td>
                <button class="btn-link red tombstone-link" data-node="{{node}}" data-topic="{{../name}}" style="padding: 0 6px; border: 0;">✘</button>
                {{#if show_broadcast_address}}
                {{hostname_port}} (<a class="link" href="{{basePath "/nodes"}}/{{node}}">{{node}}</a>)
                {{else}}
                <a class="link" href="{{basePath "/nodes"}}/{{node}}">{{hostname_port}}</a>
                {{/if}}
```

**Comment by andyxning** [comment]
@ploxiln I have tested this locally. But it can not be operated successfully.





Have you test this PR against non localhost ipv6 address?

**Comment by andyxning** [comment]
@ploxiln I have investigated this further. It turns out that something has changed after v0.3.8, which we use internally. I have tested your changes against master branch, it is ok. And i think we can merge this. :)

As for our cases, we need to just merge #1185 internally since it is based on v0.3.8. :)

**Comment by ploxiln** [comment]
> It turns out that something has changed after v0.3.8, which we use internally.

Thanks explains the confusion :)
Thank you for identifying the problem and testing this!

**Comment by andyxning** [comment]
I think we can merge this for now. But i have no merge right. 

BTW, what about the request about promoting myself to be a NSQ member?

**Comment by ploxiln** [comment]
yeah, was just giving some more comment time before merge :)

It turns out I actually don't have sufficient privileges to add other members to the organization, I will ping some people about that.

**Comment by andyxning** [comment]
> It turns out I actually don't have sufficient privileges to add other members to the organization, I will ping some people about that.

Thanks for your help @ploxiln . Any more details we can chat on email. :)

**Pull request merged**
