### PR TITLE
nsqadmin: make "rate" column work without --proxy-graphite

### PR DESCRIPTION
**Pull request by ploxiln**
graphite /render requests for "rate" would always be proxied through nsqadmin, even without --proxy-graphite enabled. I figured out a way to make it work more like the graphite images do.

I imagine this won't win any frontend code-style awards, and welcome comments related to that.

I left the /graphite handler in nsqadmin in case someone has custom frontend templates they want to continue using, but do you think I should remove it?

### CODE REVIEW

**Comment by mreiferson** [comment]
got sshots to prove this works


wayyyyyyyyyyy to much javascript to review on a friday night man

**Comment by mreiferson** [comment]
:heart:

**Comment by ploxiln** [comment]
sure.
btw "dockerdev", "nsqadmin.dockerdev", "graphite.dockerdev" are my dev VM

### before

screen shot 2016-04-09 at 00 15 46

_nsqadmin log_
```
[nsqadmin] 2016/04/09 04:15:36.308407 GRAPHITE: http://graphite.dockerdev/render?format=json&from=-120sec&target=sumSeries%28nsq.%2A.topic.events.message_count%29&until=-60sec
[nsqadmin] 2016/04/09 04:15:36.308931 ERROR: graphite request failed - got response 401 Unauthorized "<html>\r\n<head><title>401 Authorization Required</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>401 Authorization Required</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"
```

### after

screen shot 2016-04-09 at 00 19 00

_browser request_
```
GET /render?jsonp=jQuery223032047556238993613_1460175537694&target=sumSeries(nsq.*.topic.events.message_count)&from=-120sec&until=-60sec&format=json&_=1460175537695 HTTP/1.1
Host: graphite.dockerdev
...
Referer: http://nsqadmin.dockerdev/
Authorization: Basic *****
...

HTTP/1.1 200 OK
Server: nginx
Date: Sat, 09 Apr 2016 04:18:58 GMT
Content-Type: text/javascript
Transfer-Encoding: chunked
...

jQuery223032047556238993613_1460175537694([{"target": "sumSeries(nsq.*.topic.events.message_count)", "datapoints": [[2.0, 1460175420]]}])
```

### with --proxy-graphite

well, same screenshot, it works

_browser request_
```
GET /render?jsonp=jQuery22309552545633412136_1460177590870&target=sumSeries(nsq.*.topic.events.message_count)&from=-120sec&until=-60sec&format=json&_=1460177590871 HTTP/1.1
Host: nsqadmin.dockerdev
...
X-UserAgent: nsqadmin/v0.3.7
X-Requested-With: XMLHttpRequest
Referer: http://nsqadmin.dockerdev/
Authorization: Basic *****
...

HTTP/1.1 200 OK
Server: nginx
Date: Sat, 09 Apr 2016 04:53:11 GMT
Content-Type: text/javascript
Content-Length: 147
...

jQuery22309552545633412136_1460177590870([{"target": "sumSeries(nsq.*.topic.events.message_count)", "datapoints": [[2.0, 1460177520]]}])
```

It's worth noting that there are zero log messages in nsqadmin for these proxied requests, and also they are sent without changing the Host header, so to actually make it work I had to e.g. change --graphite-url to `http://localhost:9090` to bypass the nginx subdomain proxying setup I've got here. Anyway, it doesn't make sense to add a bunch of options to support setups besides connections directly to graphite-web for this case, just clarifying the tested config.

**Comment by mreiferson** [comment]
LGTM, thanks plo

**Pull request merged**
