### PR TITLE
nsqadmin: update bindata after "delfate" typo fix

### PR DESCRIPTION
**Pull request by ploxiln**
follow-up to #1005 
hard to review this bindata unfortunately ... I just did

  * `npm install`
  * `gulp clean build`
  * `go-bindata --pkg=nsqadmin --prefix=static/build static/build/...`

### CODE REVIEW

**Comment by ploxiln** [comment]
Don't merge yet, I'm still seeing Delfate in nsqadmin when I try to test this

**Comment by ploxiln** [comment]
I think that `./gulp clean build` at once doesn't work, but `./gulp clean` and then `./gulp build` does

**Comment by ploxiln** [comment]
alright, looks good now

**Comment by mreiferson** [comment]
thanks plo

**Pull request merged**
