### PR TITLE
nsqd: optimize memory for short client conn

### PR DESCRIPTION
**Pull request by absolute8511**
reuse the bufio reader and writer to reduce memory malloc so we can reduce gc.

### CODE REVIEW

**Comment by mreiferson** [comment]
@absolute8511 thanks for proposing these changes!  I'm curious if you have any data indicating this is an actual issue impacting GC.

Relative to the potential for allocations due to incoming message volume, I would expect that client connections would have a much lower overall impact.

**Comment by fjjiaboming** [comment]
Show some data for proof.

**Comment by absolute8511** [comment]
By benching the tcp short live connection with PUB, I got the data below:

Both startup with `GOMAXPROCS=24 ./nsqd`, and bench with 2 machines, each 1000 goroutines, connection no keepalive, running for 100 seconds, pub 100bytes one by one.

before changes:

```
 1.395mb/s - 14628.695ops/s - 68.359us/op (client 1)
 1.386mb/s - 14531.496ops/s - 68.816us/op (client 2)

# runtime.MemStats
# Alloc = 24892432
# TotalAlloc = 104956714696
# Sys = 48015608
# Lookups = 5908857
# Mallocs = 184981010
# Frees = 184929716
# HeapAlloc = 24892432
# HeapSys = 40058880
# HeapIdle = 13467648
# HeapInuse = 26591232
# HeapReleased = 0
# HeapObjects = 51294
# Stack = 2932736 / 2932736
# MSpan = 224328 / 294912
# MCache = 28800 / 32768
# BuckHashSys = 1456888
# NextGC = 26998864
# PauseNs = [982914 1260784 1040274 1070357 1020809 1279138 1187023 1378707 1066520 962381 1418936 1004952 1031791 1131756 949611 1034408 987327 1024463 1150847 1038265 1030638 1068268 1051880 1042374 1052005 1389708 1030829 1379405 1420518 1002707 898825 744186 870678 897686 872521 975214 1018969 808071 651439 917674 991191 968052 955316 917922 884764 941439 963624 879636 894317 930618 910189 960663 942605 986479 862782 950242 891484 903217 930529 997259 902069 956042 924726 929353 1010569 1003483 1000159 883847 815388 889630 911448 1060883 979330 923900 746610 952062 991505 784551 767395 969377 856955 945615 1014754 1022338 934962 926119 803277 1058453 957103 695332 955730 938142 1080499 725532 918065 716572 934113 820427 964245 846505 779108 1072204 807156 885666 1003399 957374 995517 874835 955949 841977 948405 916808 868942 1046782 1027498 769264 1004552 924418 961480 944487 1010476 816137 1028637 816100 1129997 1027980 952483 953292 1044977 932897 822694 1365068 862459 934195 904319 852051 892933 962834 741228 930928 1016709 977563 1008050 914800 1065338 1096051 758939 923474 1113120 725920 906274 855755 874599 961207 892155 1086559 994305 990565 1228868 1129125 905168 946285 1121534 939796 983092 962143 891651 997886 812861 895848 662728 980245 948649 924744 1055788 955740 1095253 764431 1015509 807550 1065055 1142414 954715 841919 1141868 964213 770016 972988 1019948 770323 805671 1097081 775230 741353 1062413 947126 995064 943992 1351712 1002856 1005684 1039365 1070960 912366 1222261 974627 952304 888748 762447 989000 1139678 771946 955344 905350 1108966 937362 989574 928742 960275 1048468 901524 865554 892663 826138 935150 856174 974472 990845 938213 855301 1093939 945275 855768 942038 832335 1012339 1018824 882973 681148 696998 913381 915684 985677 1025196 1248124 1106070 1058886 1504118 1061975 1866309 1874491 1090433 1004355 1009356 1188266 1298733]
# NumGC = 24093
# EnableGC = true
# DebugGC = false

```

after changes:

```
1.598mb/s - 16753.355ops/s - 59.690us/op
1.586mb/s - 16633.586ops/s - 60.119us/op

# runtime.MemStats
# Alloc = 13487816
# TotalAlloc = 50888975904
# Sys = 26827000
# Lookups = 6783223
# Mallocs = 209393976
# Frees = 209339425
# HeapAlloc = 13487816
# HeapSys = 20234240
# HeapIdle = 5062656
# HeapInuse = 15171584
# HeapReleased = 0
# HeapObjects = 54551
# Stack = 2834432 / 2834432
# MSpan = 202072 / 245760
# MCache = 28800 / 32768
# BuckHashSys = 1456576
# NextGC = 14831568
# PauseNs = [1044412 972990 1291214 1385533 941360 878177 964621 1072966 1008170 1253428 948032 1194003 973793 1045293 1097973 977620 1060461 1055417 911123 1010788 1054354 1068901 1020013 1086099 1070580 1173687 943556 955084 1419069 1246054 996366 1005310 1004232 928110 1105394 1113979 1035894 758609 1147500 1045006 1029129 724546 1033446 1042403 1087072 1074739 963336 940510 994852 938448 910713 1011417 1571662 1008900 979424 970034 912549 913032 1059048 951625 1012949 994450 1505671 1112188 968397 917346 1017145 934921 970769 965402 1055656 1019550 965372 961572 1157835 972926 947997 971364 1005858 1841069 937505 1085665 1047122 1092879 1955646 1011440 983248 993518 980490 1124282 968704 1033214 879484 1110884 889723 986324 968201 967442 847486 748762 1033756 963221 1766786 988811 948797 1072847 1019237 988802 974750 1098157 1077867 1101951 1043170 934284 1144914 1039737 1045724 986014 1095806 1032436 1058384 802661 1092599 963574 1021368 1092788 1169718 1002990 1119839 822666 815036 939538 940937 1580136 976788 933328 1117790 911152 758756 1338177 1032048 1006024 970877 1167924 1010607 1149123 928545 791607 1001290 1088530 1005691 1017560 1061075 888015 971403 1163282 946987 990089 720918 1108701 1037892 875913 912038 941984 1042977 827978 947437 949384 1244209 1028032 976410 914881 946454 993082 916996 1039037 802134 1428231 998835 915422 825209 1053235 1021294 977751 793481 919344 1013918 1070181 1015961 1040007 913464 1444973 930219 972206 1002837 1085043 945311 982640 1615830 962030 1051565 947393 759172 1045667 1334450 973704 976744 972797 991579 1100211 967520 838379 778939 814701 939419 904190 1048463 937265 1160038 1022284 961452 1038005 1089266 909452 1125775 983286 1257920 1078861 1023486 929925 1147693 926196 945042 939473 1072924 739326 1039723 966432 1192068 1048480 1217235 1084268 1011485 1030645 966016 765346 714973 1106727 1015566 936194 925769 1097339 1001958 940812 869885 1008031]
# NumGC = 13148
# EnableGC = true
# DebugGC = false
```

It shows we can get both TPS improvement and GC time reduce. (NumGC almost half of previous)

**Comment by mreiferson** [comment]
Well, sure, in that pathological case it makes sense that it would reduce GC pressure.  I'm not sure how much investment we should make optimizing a use case that isn't recommended and incredibly inefficient.

What's the motivation for churning through connections when publishing?

**Comment by absolute8511** [comment]
Our use case is under php. All the php-fpm processes use the pub with short live connections.

**Comment by mreiferson** [comment]
@absolute8511 in that case, you should use HTTP to publish which would support this more effectively

**Comment by absolute8511** [comment]
I think HTTP should be more complex so it should be a little slower than the optimized tcp.

**Comment by mreiferson** [comment]
> I think HTTP should be more complex so it should be a little slower than the optimized tcp.

I recommend testing it - I would expect the code to be simpler and the performance to be at least comparable (and, if you can pool your HTTP connections, better performance).

**Comment by absolute8511** [comment]
I have done some bench test with http pub, and the data is below:

```
HTTP PUB:
QPS:17158.201598223008
QPS:17065.946202453724

short TCP PUB
19376.900ops/s
19297.111ops/s
```

both with two clients on different machines with the same concurrency. Maybe it is not the great improvement, but I see a necessary if performance is needed.

**Comment by mreiferson** [comment]
> but I see a necessary if performance is critical.

If performance is critical it would make sense to maintain long-lived connections and publish over the TCP protocol via `MPUB`, not either of these methods.

**Comment by absolute8511** [comment]
Maybe our use case is somehow special so we can not maintain long-lived connections. I agreed that if possible `MPUB` with long-lived connections is always the right way to get the best performance.
To expect the code to be simpler, maybe we can leave this just as a suggestion.

**Comment by mreiferson** [comment]
@absolute8511 agreed, thank you for your contributions!

**Pull request closed without merging**
