### PR TITLE
travis: update go versions

### PR DESCRIPTION
**Pull request by dvrkps**

### CODE REVIEW

**Comment by andyxning** [comment]
@dvrkps I don't think we need to keep backward compatibility with Golang 1.6 anymore since 1.9 has been released. Keep backward compatibility for latest three major Golang versions should be fine.

@mreiferson @ploxiln WDYT.

**Comment by andyxning** [comment]
BTW, seems the error in travisCI has nothing to do this change. @mreiferson @ploxiln PTAL.

**Comment by mreiferson** [comment]
pushed a few commits here, tests should pass 🤞

**Comment by mreiferson** [comment]
thanks @dvrkps

**Pull request merged**
