### PR TITLE
release prep

### PR DESCRIPTION
**Pull request by ploxiln**
The Changelog is a bit of work so I figured I'd get started on it. I'm about half through it (the older half).

please take a look and feel free to suggest wording changes @jehiah @mreiferson

side note: when might we remove the deprecated `--verbose` flag? a couple releases hence I suppose?

### CODE REVIEW

**Comment by ploxiln** [comment]
Finished the second half of the changelog updates, bringing it up to present day.

I'll leave this PR open until we're ready to tag 1.1.0-rc1

**Comment by mreiferson** [comment]
LGTM, thanks!

**Comment by mreiferson** [comment]
@ploxiln want to squash this down so we can get it in?

**Comment by ploxiln** [comment]
squashed changelog commits into one

I thought @jehiah might have planned to work on an nsadmin js-libs/bindata update ...

**Comment by mreiferson** [comment]
Oh, right, that can happen separately anyway.

**Pull request merged**
