### PR TITLE
nsq_tail: added -gunzip option

### PR DESCRIPTION
**Pull request by 3dbrows**
* if the -gunzip option is set, an attempt is made to gunzip the message before output
* if the -gunzip option is set but the message was not gzipped, do not alter the message

### CODE REVIEW

**Comment by 3dbrows** [comment]
Ready for review. Please see #1303

**Comment by jehiah** [comment]
@3dbrows can you give some context of why or when this would be preferable vs sending an un-gzipped message body? NSQ provides gzip (or snappy) compression on the transport level by default which minimizes the need to manually compress message body in most cases.

**Comment by mreiferson** [comment]
Granted that `nsq_tail` does make some assumptions about the encoding of messages (line oriented text), however I don't think that we want to start baking in other formats.

Thanks for the proposed contribution, gonna close.

**Comment by 3dbrows** [comment]
@jehiah I hadn't appreciated that NSQ compresses by default, thanks for pointing that out. In that case it is unnecessary for me to manually compress at the application level. 👍

**Pull request closed without merging**
