### PR TITLE
diskqueue ReadChan now receive-only chan

### PR DESCRIPTION
**Pull request by bitpeng**
ReadChan return receive-only chan for reading, I also open a pr for https://github.com/nsqio/go-diskqueue/pull/7

### CODE REVIEW

**Comment by bitpeng** [comment]
@ploxiln @mreiferson

**Comment by ploxiln** [comment]
please update `Gopkg.toml`, and run dep to update `Gopkg.lock`, so that non-module builds of nsq still work (and that will also fix the tests)

**Comment by bitpeng** [comment]
> please update `Gopkg.toml`, and run dep to update `Gopkg.lock`, so that non-module builds of nsq still work (and that will also fix the tests)

@ploxiln done, please review the code. thanks

**Comment by ploxiln** [comment]
Looks good. Can you please squash the commits down to one? (We like to have both a merge commit, and cleaned-up git history.) Thanks :)

**Comment by bitpeng** [comment]
@ploxiln Sorry, I am not really familiar with Git. Is that ok? thanks

**Comment by ploxiln** [comment]
yup, that worked

**Pull request merged**
