### PR TITLE
nsq_tail multi-topic and build stuff

### PR DESCRIPTION
**Pull request by ploxiln**
I just squashed and re-titled the commits from #957

### CODE REVIEW

**Comment by ploxiln** [comment]
@mreiferson I could also squash all the build-related commits together if you like

**Comment by ploxiln** [comment]
I also added a tweak to the stopping, see the last commit @soar

**Comment by mreiferson** [comment]
@ploxiln LGTM, you want to leave that last commit separate?

**Comment by mreiferson** [comment]
also, I think this is another case where you could push to the original PR's branch instead?

**Comment by soar** [comment]
How this PR got increased coverage with same changes as mine? :-D

**Comment by ploxiln** [comment]
the coverage fluctuates randomly, one of these days I'll get around to figuring out why :)

**Comment by ploxiln** [comment]
I'll squash my fix in. I didn't think of the fact that I might be able to push to the original branch because I'm an admin, I'll try it ...

**Comment by ploxiln** [comment]
I was able to force-push this to #957

**Pull request closed without merging**
