### PR TITLE
 add a interface to get topic information for app developer to make decision

### PR DESCRIPTION
**Pull request by Chaiyq**
in development, we need to determine production and consumption status, especially in high availability scenarios, a json response is helpful.

### CODE REVIEW

**Comment by Chaiyq** [comment]
in a high availability scenario, we may start two or more nsqd, consumer may connect two or more nsqd to comsumer as well. it is important to get topic info to make decision

**Comment by Chaiyq** [comment]
this may be a perf

**Comment by ploxiln** [comment]
It looks like you can get this information from the existing `/stats` endpoint, using the `json` and `topic` params, for example:

```
$ curl -sS "http://127.0.0.1:4151/stats?format=json&topic=detection_events&include_clients=false" | jq .
{
  "version": "1.2.0",
  "health": "OK",
  "start_time": 1590539291,
  "topics": [
    {
      "topic_name": "detection_events",
      "channels": [
        {
          "channel_name": "detection-reader",
          "depth": 0,
          "backend_depth": 0,
          "in_flight_count": 0,
          "deferred_count": 0,
          "message_count": 52378124,
          "requeue_count": 0,
          "timeout_count": 124,
          "client_count": 11,
          "clients": null,
          "paused": false,
          "e2e_processing_latency": {
            "count": 0,
            "percentiles": null
          }
        }
      ],
      "depth": 0,
      "backend_depth": 0,
      "message_count": 52378124,
      "message_bytes": 12805545104,
      "paused": false,
      "e2e_processing_latency": {
        "count": 0,
        "percentiles": null
      }
    }
  ],
  "memory": {
    "heap_objects": 31628,
    "heap_idle_bytes": 9584640,
    "heap_in_use_bytes": 6930432,
    "heap_released_bytes": 8290304,
    "gc_pause_usec_100": 3203,
    "gc_pause_usec_99": 1282,
    "gc_pause_usec_95": 660,
    "next_gc_bytes": 7672976,
    "gc_total_runs": 1461612
  },
  "producers": []
}
```

**Comment by Chaiyq** [comment]
@ploxiln, ok, Thank you for your reply

**Pull request closed without merging**
