### PR TITLE
*: staticcheck linting cleanup

### PR DESCRIPTION
**Pull request by mreiferson**
These seem like mostly good things, should probably run this as part of tests too?

### CODE REVIEW

**Review by ploxiln — APPROVED** [review]

**Comment by ploxiln** [comment]
looks like i386 test is kinda broken, also go-1.17 staticcheck

**Comment by mreiferson** [comment]
OK, this should be ready to go now @ploxiln

**Review by ploxiln — APPROVED** [review]
LGTM :+1:

**Comment by ploxiln** [comment]
to summarize what I observed:
 * remove old go-bindata for go < 1.16
 * remove ssl3.0 add tls1.3
 * remove `tlsConfig.BuildNameToCertificate()` call, deprecated, "NameToCertificate" not needed anymore
 * fix ticker goroutine leak in `lookupLoop()` ?
 * remove logging from `QueryAnyAuthd()`, return one big error which is eventually logged in protocol_v2.go
 * remove bits of dead code
 * mechanical cleanups with no functional change (ioutil renames, type switch cleanup ...)

All good stuff :100:

**Pull request merged**
