### PR TITLE
nsqadmin: add /config API

### LINKED ISSUE #769: nsqadmin: configuration update API
Currently nsqd has an API for updating the configuration attribute `nsqlookupd_tcp_addresses`. The same feature is needed for nsqadmin.

Also each component nsqd, nsqadmin, and nsqlookupd all support a configuration file option `config`, add support for SIGHUP to trigger reloading the configuration file and continue processing with the updated configurations.

### PR DESCRIPTION
**Pull request by kenjones-cisco**
Provides the ability to modify the configuration nsqadmin for setting
`nsqlookupd_http_addresses` to support dynamic configuration.

Closes #769

### CODE REVIEW

**Comment by kenjones-cisco** [comment]
Not sure if the failure is a common one on travis, but is related to another part of the code base that I didn't touch.

```
--- FAIL: TestDiskQueueSyncAfterRead (0.13s)
```

**Comment by kenjones-cisco** [comment]
@mreiferson As part of working on this I created 2 Dockerfiles for testing nsq against both golang1.5 and golang1.6, and a small bash script to build the image and run `test.sh` using the images built.

Would there be interest in me creating a PR to include as well? I found it useful for being able to write the code and then test against multiple versions of golang without having to maintain multiple local versions on my laptop.

**Comment by mreiferson** [comment]
@kenjones-cisco thanks for all these contributions, grateful to have you involved!

> Not sure if the failure is a common one on travis, but is related to another part of the code base that I didn't touch.

I added that test recently, it's flakey and I should fix it - I'll open an issue to track, sorry.

> Would there be interest in me creating a PR to include as well? I found it useful for being able to write the code and then test against multiple versions of golang without having to maintain multiple local versions on my laptop.

We rely on travis to run tests against multiple versions of go and 386/amd64, so I don't think we need local scripting for that.

**Comment by mreiferson** [comment]
I triggered a rebuild of the one that failed, we're 💚

**Comment by mreiferson** [comment]
Code LGTM, would you mind changing the commit message on this to follow our convention `nsqadmin: add /config API`?

Thanks!

**Comment by kenjones-cisco** [comment]
Sure, missed that one detail.

**Comment by thoughtexchange** [comment]
Thanks for this addition!  This makes our deployment simpler as now both nsqd and admin can be set with lookupd after they launch in the same way.

**Pull request closed without merging**
