### PR TITLE
tests: use GitHub Actions for CI

### PR DESCRIPTION
**Pull request by ploxiln**
also add go-1.14 and go-1.15 to test matrix

TODO: try to add back coveralls

### CODE REVIEW

**Comment by ploxiln** [comment]
sometimes this starts working right away, sometimes this file has to exist in master before it'll trigger on and use the changes in the pull requests ...

**Comment by ploxiln** [comment]
@mreiferson @jehiah do you mind if I merge this in order to get GitHub Actions enabled, and then finish it up in a follow-up PR? (changes to the actions take effect in the PR, but it has to exist in master to be enabled, I think?)

see also https://docs.travis-ci.com/user/migrate/open-source-repository-migration/#q-what-will-happen-to-travis-ciorg-after-december-31st-2020

**Review by jehiah — APPROVED** [review]

**Comment by ploxiln** [comment]
thanks

**Comment by ploxiln** [comment]
aha, it did trigger https://github.com/nsqio/nsq/actions/runs/348930257

**Comment by mreiferson** [comment]
thanks for this ❤️

**Pull request merged**
