### PR TITLE
nsq_to_file: rewrite function hasArg

### PR DESCRIPTION
**Pull request by KerwinKoo**
Recently I'm reading the source code of NSQ.I think using `flag.Visit` is a good idea to implement the `hasArg` func.

### CODE REVIEW

**Comment by mreiferson** [comment]
thanks @KerwinKoo, would you mind squashing down to one commit?

**Comment by KerwinKoo** [comment]
@mreiferson I squashed down to one commit，but it shows ` The Travis CI build failed `

**Comment by mreiferson** [comment]
thanks, I just realized there are two more instances of `hasArg` in the codebase:

https://github.com/nsqio/nsq/blob/085d69c8dbb94226c2882edd1929444d215f5dc7/apps/nsq_to_http/nsq_to_http.go#L159
https://github.com/nsqio/nsq/blob/085d69c8dbb94226c2882edd1929444d215f5dc7/apps/nsq_to_nsq/nsq_to_nsq.go#L258

**Comment by KerwinKoo** [comment]
@mreiferson I'm sorry to commit it so late, I send a new pull request #712 to solve the same problem.

**Pull request closed without merging**
