### PR TITLE
internal/util: new UniqRands() implementation

### PR DESCRIPTION
**Pull request by ploxiln**
using the Fisher-Yates shuffle algorithm

faster and more consistent runtime when
quantity is near maxval (aka l is near n)

### CODE REVIEW

**Comment by ploxiln** [comment]
Benchmark recap. Before:

```
BenchmarkUniqRands5of5-4         2000000               887 ns/op
BenchmarkUniqRands20of20-4        200000              6932 ns/op
BenchmarkUniqRands20of50-4        500000              3432 ns/op
```

After:

```
BenchmarkUniqRands5of5-4         5000000               228 ns/op
BenchmarkUniqRands20of20-4       2000000               832 ns/op
BenchmarkUniqRands20of50-4       2000000               885 ns/op
```

**Comment by ploxiln** [comment]
@vearne does this look good to you?

(Notice that I kept the author name/email of your commit, but your email address in your commit is not associated with your github account.)

**Comment by vearne** [comment]
@ploxiln  I have add a email and associated with my github account.

**Comment by ploxiln** [comment]
Cool. We don't require it, I just figured you might wonder why the commit doesn't seem to credit your github account.

**Pull request merged**
