### PR TITLE
nsqadmin: --proxy-graphite option is broken

### PR DESCRIPTION
**Pull request by mreiferson**
* nsqadmin v1.2.0 (built w/go1.12.9)
* cmd works:
  * `./bin/nsqadmin --lookupd-http-address=${localip}:4161 -graphite-url=http://${localip}:80`
* cmd  cause whole site down:
  * `./bin/nsqadmin --lookupd-http-address=${localip}:4161 -graphite-url=http://${localip}:80 -proxy-graphite `

## there is a js error in browser: 
* `Uncaught SyntaxError: Unexpected token ';'`
## index page shows:
```
<script type="text/javascript">
        var USER_AGENT = 'nsqadmin/v1.2.0';
        var VERSION = "1.2.0";
        var GRAPHITE_URL = ;
        var GRAPH_ENABLED = true;
        var STATSD_COUNTER_FORMAT = "stats.counters.%s.count";
        var STATSD_GAUGE_FORMAT = "stats.gauges.%s";
        var STATSD_INTERVAL =  60 ;
        var STATSD_PREFIX = "nsq.%s";
        var NSQLOOKUPD = ["127.0.0.1:4161",];
        var IS_ADMIN =  true ;
        var BASE_PATH = "/";
    </script>
```
the <kbd>GRAPHITE_URL</kbd>      is empty

### CODE REVIEW

**Comment by mreiferson** [comment]
Interesting... I used `hub` to convert this issue to a PR, and it looks like I became the original author????????

**Comment by mreiferson** [comment]
Anyway, what a fun Saturday night! This updates `nsqadmin` static dependencies (e.g. Gulp) to work with Node 14.x, updates  `gulpfile.js`, and rebuilds static assets using the maintained version of `go-bindata` (all to pickup this two character fix 
17f69f1).

WARNING: 🟥  I haven't tested any of this... 🔴

**Comment by ploxiln** [comment]
I can test the non `--proxy-graphite` case, hopefully soon ...

@fanlix can you compile nsqadmin from this branch and try it for your `--proxy-graphite` setup?

**Comment by fanlix** [comment]
@ploxiln ok. I will do it today.

**Comment by fanlix** [comment]
# bad news, this patch not work.

* complie by:  `CGO_ENABLED=0 make BLDFLAGS='-ldflags="-s -w"' nsqadmin`
* run with graphite options, fail
* run without graphite options, fail:  `./nsqadmin  --lookupd-http-address=127.0.0.1:4161` 

## nsqadmin access logs looks ok
```
[nsqadmin] 2020/10/12 12:50:52.884786 INFO: nsqadmin v1.2.1-alpha (built w/go1.14.2)
[nsqadmin] 2020/10/12 12:50:52.885118 INFO: HTTP: listening on [::]:4171
[nsqadmin] 2020/10/12 12:50:55.666282 INFO: 200 GET / (xxxx:23251) 89.628µs
[nsqadmin] 2020/10/12 12:50:56.731998 INFO: 200 GET / (xxxx:23251) 39.213µs
```

## but browser gets blank page
```
curl -i http://xxxx:4171/

HTTP/1.1 200 OK
Content-Type: text/html
Date: Mon, 12 Oct 2020 04:57:30 GMT
Content-Length: 0
```

## the 2-char modify in index.html is the right fix
* I modify index.html in browser-dev-tool, add that 2-char by hand. <kbd>it works.</kbd>
* but gulp/binddata hard to handle. :(

**Comment by ploxiln** [comment]
yeah, the bindata which mreiferson generated seems to be messed up, I also get blank pages:

```
$ curl -v localhost:4171/topics
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 4171 (#0)
> GET /topics HTTP/1.1
> Host: localhost:4171
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: text/html
< Date: Mon, 12 Oct 2020 05:42:30 GMT
< Content-Length: 0
< 
* Connection #0 to host localhost left intact
* Closing connection 0
```

**Comment by ploxiln** [comment]
the build of go-bindata I happen to have installed seems to work better, I went ahead pushed up the result to this branch

**Comment by ploxiln** [comment]
(also it seems travis-ci results aren't being posted here, but the CI is running and can be seen at https://travis-ci.org/github/nsqio/nsq/pull_requests)

**Comment by mreiferson** [comment]
What do you mean by “installed”? The question I have is whether it’s the version of go-bindata I’m using or node/gulp/my changes not producing correct static assets as input.

I’ll check locally tomorrow (replying on mobile)

**Comment by ploxiln** [comment]
I just mean I built this go-bindata and put it in my PATH about a year ago:

```
$ ls -l ~/go/bin/go-bindata 
-rwxr-xr-x  1 pierce  staff  2882872 Sep 11  2019 /Users/pierce/go/bin/go-bindata
$ go-bindata --version
go-bindata 3.1.3 (Go runtime go1.12.9).
Copyright (c) 2010-2013, Jim Teeuwen.
```

I don't think that singularly narrows down the fork I used, but I think it's older than the suggested fork you put in the README ...

**Comment by mreiferson** [comment]
The latest version of go-bindata that I used changed the behavior of the `--prefix` argument, requiring a trailing `/` in order to produce the right keys in the `_bindata` map.

**Comment by ploxiln** [comment]
cool, I'll test it out

**Comment by fanlix** [comment]
by my test  **it works**, for both proxy and un-proxy. 👍

**Review by ploxiln — APPROVED** [review]
All looks good and works fine for me. Should probably just squash commits a bit.

**Pull request merged**
