### PR TITLE
nsqadmin: update header

### PR DESCRIPTION
**Pull request by jehiah**
This adds the nsq logo, and a link to nsq.io

### CODE REVIEW

**Comment by jehiah** [comment]
Looks like this now: 

screen shot 2015-09-22 at 11 14 34 am

**Comment by jehiah** [comment]
RFR/RFM @mreiferson After this lands i'll update nsq.io to match the logo placement.

**Comment by mreiferson** [comment]
👍🏻

**Comment by jehiah** [comment]
oops i screwed up this commit. I'm going to push a fix to master to actually reflect what this commit was supposed to have =)

**Pull request merged**
