### PR TITLE
gofmt

### PR DESCRIPTION
**Pull request by whilei**
Just ran

	gofmt -w .

on the project root. That's all.

https://blog.golang.org/go-fmt-your-code

---
> I made this PR with a project going on over at https://github.com/rotblauer/gofmt-att, and it's definitely a work in progress. So if I got something wrong, or this is annoying at all, please file an issue over there and we'll sort it out.

### CODE REVIEW

**Comment by ploxiln** [comment]
I'd rather not give this spammy github-crawling thing, which found a single extra blank line, the benefit of a commit in this repo. I'll fix and push up myself to avoid other opportunistic automated things from triggering on it.

**Comment by ploxiln** [comment]
bf74c94e1628b4b95e152b89d50c4c1ca54c6224

**Comment by judwhite** [comment]
@ploxiln Who doesn't use `-s`? Amateurs

**Comment by whilei** [comment]
Sorry if my robot bothered you, he's fairly simple-minded (and isn't out to gain the "benefit"s of commits in repos... whatever those are).

I won't trouble you with another PR, and I don't mean to beat a dead horse, but here's a code simplification change you can use if you want. https://github.com/whilei/nsq/commit/93b8458aba6e7f4dbdbf3fbef1f13cdbf0fa798b

**Pull request closed without merging**
