### PR TITLE
*: add helm chart

### PR DESCRIPTION
**Pull request by Zhang21**
nsq helm chart:

- nslookupd
- nsqd
- nsqadmin

<br>

Deploy nsq to k8s quickly by helm.

### CODE REVIEW

**Comment by mreiferson** [comment]
Thanks for submitting this. My intuition is that this should probably be in a separate repo under the `nsqio` org? How do open source projects usually structure this in the k8s community?

(also, sigh that's a lot of YAML)

**Comment by Zhang21** [comment]
> Thanks for submitting this. My intuition is that this should probably be in a separate repo under the `nsqio` org? How do open source projects usually structure this in the k8s community?
> 
> (also, sigh that's a lot of YAML)

Both, separate repo or souce code repo.

**Comment by LordNoteworthy** [comment]
Hi @mreiferson 

This should be on a separate repo under the `nsqio` org.

Most orgs create a new repository which they call: `helm-chart` or a folder in the root repo `nsqio/nsq` called `helm`. I would suggest going with the first approach.

Once the git repo get created, we can submit a PR there.

I would suggest starting with this: https://github.com/BeeInventor/charts/tree/main/beeinventor/nsq as I have been running in prod with no issue.

This PR looks good but there are few problems which can be easily fixed.

**Comment by mreiferson** [comment]
@ploxiln created https://github.com/nsqio/helm-chart

**Comment by ploxiln** [comment]
I pushed up the initial commit to https://github.com/nsqio/helm-chart copying the BeeInventor nsq chart (moved to the root of the repo as discussed). Please open pull requests on that repo for updating the install instructions in the README, and please give some tips in the PRs there for how we should publish the chart. Thanks!

**Pull request closed without merging**
