### PR TITLE
nsqd: remove channel messagePump

### PR DESCRIPTION
**Pull request by mreiferson**
(Pushing up rebased branches I've had laying around locally for ages)

This removes a goroutine per channel and simplifies exit logic.

### CODE REVIEW

**Comment by mreiferson** [comment]
Also, w/r/t concurrency, because each _client_ is now selecting on mem/disk, a slow disk read won't block concurrent clients from being able to proceed reading from incoming messages on the mem channel.

**Comment by mreiferson** [comment]
any thoughts on this one

**Comment by judwhite** [comment]
I'll have to sit down with this one to fully understand it. I planned on looking into the ID perf one later this week and doing some bench tests. So, no, nothing yet from me :smiley:

**Comment by ploxiln** [comment]
I'm no expert, but I like this change. Removes a goroutine and chan per nsq channel, a handoff per message, net lines of code, and seems to accomplish the same end result.

**Comment by jehiah** [comment]
👍  ready for this to land?

**Comment by mreiferson** [comment]
yep

```
benchmark                           old ns/op     new ns/op     delta
BenchmarkProtocolV2MultiSub1-4      5115          4364          -14.68%
BenchmarkProtocolV2MultiSub2-4      7466          6449          -13.62%
BenchmarkProtocolV2MultiSub4-4      13076         11632         -11.04%
BenchmarkProtocolV2MultiSub8-4      25147         22599         -10.13%
BenchmarkProtocolV2MultiSub16-4     55787         45889         -17.74%

benchmark                           old MB/s     new MB/s     speedup
BenchmarkProtocolV2MultiSub1-4      50.04        58.65        1.17x
BenchmarkProtocolV2MultiSub2-4      68.57        79.39        1.16x
BenchmarkProtocolV2MultiSub4-4      78.31        88.03        1.12x
BenchmarkProtocolV2MultiSub8-4      81.44        90.62        1.11x
BenchmarkProtocolV2MultiSub16-4     73.42        89.26        1.22x
```

**Comment by mreiferson** [comment]
🔥

**Pull request merged**
