### PR TITLE
readme.md Add New Company 夸父炸串 In Production

### PR DESCRIPTION
**Pull request by ritaswc**
ready for review

### CODE REVIEW

**Comment by mreiferson** [comment]
@ritaswc thanks! These logos first get added to the nsqio/nsqio.github.io repo, for example here: https://github.com/nsqio/nsqio.github.io/commit/dcc1fe356e3c676f3bf8c4cc6b1f6ba9eb9a9199

Then we link to that static asset here in this PR.

**Comment by ritaswc** [comment]
> @ritaswc thanks! These logos first get added to the nsqio/nsqio.github.io repo, for example here: [nsqio/nsqio.github.io@dcc1fe3](https://github.com/nsqio/nsqio.github.io/commit/dcc1fe356e3c676f3bf8c4cc6b1f6ba9eb9a9199)
> 
> Then we link to that static asset here in this PR.

Please check this PR, Thanks

https://github.com/nsqio/nsqio.github.io/pull/88

**Comment by mreiferson** [comment]
Merged, can you please update this PR with the new URL?

**Comment by ritaswc** [comment]
> Merged, can you please update this PR with the new URL?

Updated，Thanks

**Pull request merged**
